# 配置tomcat端口号
server:
  port: 9002

# 配置rabbitmq
spring:
  rabbitmq:
    host: 10.2.15.99   #mq地址
    port: 5672        #端口
    username: guest   #登录账号
    password: guest   #登录密码
    virtual-host: /   #虚拟机
    #publisher-confirms: true # 开启消息发送确认机制,低版本
    # 开启消息发送确认机制
    publisher-confirm-type: correlated #交换机确认
    publisher-returns: true #队列确认
