# 配置tomcat端口号
server:
  port: 9004

# 配置rabbitmq
spring:
  rabbitmq:
    host: 10.2.15.99   #mq地址
    port: 5672        #端口
    username: guest   #登录账号
    password: guest   #登录密码
    virtual-host: /   #虚拟机          #虚拟机
    #publisher-confirms: true # 开启消息发送确认机制,低版本(一般在生产端，消费端加上也没关系)
    publisher-confirm-type: correlated # 开启消息发送确认机制(一般在生产端，消费端加上也没关系)
    listener:
      simple:
        # 并发消费：每个侦听器线程的最小数量，具体数值根据系统性能配置（一般为系统cpu核数）
        concurrency: 2
        # 并发消费：每个侦听器线程的最大数量，具体数值根据系统性能配置（一般为系统cpu核数*2）
        max-concurrency: 4
        # 每次只能获取一条消息，处理完成才能获取下一个消息,避免照成消息堆积在一个消费线程上
        prefetch: 1
        #acknowledge-mode: manual         # 消费者开启手动ack消息确认，需要测试请看示例请AckConsumer,所有队列都会生效
        #default-requeue-rejected: false  # 设置为false，会重发消息到死信队列（防止手动ack确认失败的消息堆积），需要测试请示例AckConsumer,所有队列都会生效
        retry:
          enabled: true                   # 解决消息死循环问题-启用重试
          max-attempts: 3                 # 最大重试3次(默认)，超过就丢失（或放到死信队列中，防止消息堆积）
          multiplier: 2                   # 乘子
          initial-interval: 3000          # 第一次和第二次之间的重试间隔，后面的用乘子计算 3s 6s 12s
          max-interval: 16000             # 最大重试时间间隔16s